Please enter the commit message for your changes. Lines starting  with '' will be ignored, and an empty message aborts the commit.
 On branch taglio-23062021
 Your branch is up to date with 'origin/taglio-23062021'.

 Changes to be committed:
	modified:   README.md
	modified:   upgrade_ubnt

diff --git a/upgrade_ubnt b/upgrade_ubnt
--- a/upgrade_ubnt
+++ b/upgrade_ubnt
@@ -11,6 +11,10 @@ basedir=$(pwd)
 defaultinterface=$(ip route | grep default | awk '{print $5}')
 ipv4interface=$(ifconfig $defaultinterface | awk 'FNR == 2 {print}' | awk '{print $2}')
 localdomainname=$(dig -x $ipv4interface +short | sed "s/$(hostname).//" | sed 's/.$//')
+uid=$(id -u)
+userna=$(id -nu $uid)
+BACKUP="/home/$userna/Backup/ubigator"
+datarelease=$(date +"%d%m%Y%H%m%S")
 
 if [[ $# -eq 0 ]]; then
 	echo -e $0 "have to be used with the following options \
@@ -20,6 +24,10 @@ if [[ $# -eq 0 ]]; then
 			\n"
 	
 	exit 1
+fi
+
+if [[ ! -d $BACKUP ]]; then
+	mkdir $BACKUP
 fi
 
 case $1 in
@@ -118,27 +126,43 @@ case $1 in
 			echo 'Type the EdgeOS internal hostname '
 			read edgehost
 		done
-		currentfirmware=$(ssh $edgehost cat /etc/version)
-		currenthardware=$(ssh $edgehost /opt/vyatta/bin/vyatta-op-cmd-wrapper show version | awk 'FNR == 5 {print}' | awk '{print $3" "$4}')
+		currentfirmware=$(ssh -q $edgehost cat /etc/version)
+		currenthardware=$(ssh -q $edgehost /opt/vyatta/bin/vyatta-op-cmd-wrapper show version | awk 'FNR == 5 {print}' | awk '{print $3" "$4}' | tr -d '[:blank:]')
 		echo -e "Current firmware is $currentfirmware over a $currenthardware"
-		isupgradable=$(ssh $edgehost sudo /usr/sbin/ubnt-fw-latest --refresh | sed -e "s/{//" -e "s/}//" | tr , '\n' | awk 'FNR == 4 {print}' | sed "s/\"state\"://" | sed "s/\"//g")
+		isupgradable=$(ssh -q $edgehost sudo /usr/sbin/ubnt-fw-latest --refresh | sed -e "s/{//" -e "s/}//" | tr , '\n' | awk 'FNR == 4 {print}' | sed "s/\"state\"://" | sed "s/\"//g" | tr -d '[:blank:]')
 		if [[ "$isupgradable" -eq "can-upgrade" ]]; then
-			firmwareupgrade=$(ssh $edgehost sudo /usr/sbin/ubnt-fw-latest --refresh | sed -e "s/{//" -e "s/}//" | tr , '\n' | awk 'FNR == 1 {print}' | sed "s/\"version\"://" | sed "s/\"//g")
+			firmwareupgrade=$(ssh -q $edgehost sudo /usr/sbin/ubnt-fw-latest --refresh | sed -e "s/{//" -e "s/}//" | tr , '\n' | awk 'FNR == 1 {print}' | sed "s/\"version\"://" | sed "s/\"//g" | tr -d '[:blank:]')
 			ctrl=
-			echo -e "It is possible to upgrade $currentfirmware to $firmwareupgrade, procede to download?\n "
+			echo -e "It is possible to upgrade $currentfirmware to $firmwareupgrade, procede to download? "
 			read ctrl
 			case $ctrl in
 				"yes")
-					md5firmware=$(ssh $edgehost sudo /usr/sbin/ubnt-fw-latest --refresh | sed -e "s/{//" -e "s/}//" | tr , '\n' | awk 'FNR == 3 {print}' | sed "s/\"md5\"://" | sed "s/\"//g")
-					urlfirmware=$(ssh $edgehost sudo /usr/sbin/ubnt-fw-latest --refresh | sed -e "s/{//" -e "s/}//" | tr , '\n' | awk 'FNR == 2 {print}' | sed "s/\"url\"://" | sed "s/\"//g" | tr -d '[:blank:]')
+					md5firmware=$(ssh -q $edgehost sudo /usr/sbin/ubnt-fw-latest --refresh | sed -e "s/{//" -e "s/}//" | tr , '\n' | awk 'FNR == 3 {print}' | sed "s/\"md5\"://" | sed "s/\"//g" | tr -d '[:blank:]')
+					urlfirmware=$(ssh -q $edgehost sudo /usr/sbin/ubnt-fw-latest --refresh | sed -e "s/{//" -e "s/}//" | tr , '\n' | awk 'FNR == 2 {print}' | sed "s/\"url\"://" | sed "s/\"//g" | tr -d '[:blank:]')
 					tmpdir=$(mktemp -d)
 					wget "$urlfirmware" -O "$tmpdir/edgeos_firmware.rar"
 					md5downloaded=$(md5sum "$tmpdir/edgeos_firmware.rar" | awk '{print $1}')
-					for vpnc_host in $(dig openbsd.$localdomainname TXT +short | sed "s/\"//g" | tr \; '\n' | sed '$d'); do
-						echo -e "Connecting to $vpnc_host to comprobe MD5 en every hosts"
-						"md5$vpnc_host"=$(ssh $vpnc_host.$localdomainname "ftp -o /tmp/edgeos_firmware.rar $urlfirmware; md5 /tmp/edgeos_firmware.rar ; rm -rf /tmp/edgeos_firmware.rar")
-					done
-					
+					if [[ $md5firmware == $md5downloaded ]]; then
+						echo -e "MD5 verified locally proceding with international verification..."
+						for vpnc_host in $(dig openbsd.$localdomainname TXT +short | sed "s/\"//g" | tr \; '\n' | sed '$d'); do
+							echo -e "Connecting to $vpnc_host to comprobe MD5"
+							a=$(ssh $vpnc_host.$localdomainname "ftp -o /tmp/edgeos_firmware.rar $urlfirmware; md5 /tmp/edgeos_firmware.rar ; rm -rf /tmp/edgeos_firmware.rar")
+							b=$(echo $a | awk '{print $4}')
+							if [[ $b == $md5downloaded ]]; then
+								echo -e "$vpnc_host OK \n"
+							else
+								echo -e "###########################ALT MD5 FAILED IN $vpnc_host ###########################\n"
+								exit 1
+							fi
+						done
+					else
+						echo -e "###########################ALT MD5 FAILED IN $vpnc_host ###########################\n"
+						exit 1
+					fi
+					echo -e "Backing up /config directory into"
+					ssh -q $edgehost "sudo tar -czvf /tmp/backupconfig$datarelease.tar.gz /config"
+					scp -q "$edgehost:/tmp/backupconfig$datarelease.tar.gz" $BACKUP
+					ssh -q $edgehost "sudo rm -rf /tmp/backupconfig$datarelease.tar.gz"
 					rm -rf "$tmpdir/"
 				;;	
 				"no")
